### ISSUE TITLE
Formgrader not loading

### ISSUE THREAD

**Issue by henry-goluss** [jupyter/nbgrader#1910] opened 2024-08-02 21:30 UTC
Hello everyone,

First of all, big thanks for the good work!
I just started a fresh install of Jupyterhub (TLJH) and nbgrader, unfortunatly, formgrader does not load. In the console I see error : 

Refused to frame 'mydomain.com' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

### Operating system
Ubuntu 22.04.4 LTS

### `nbgrader --version`
nbgrader version 0.9.3

### `jupyterhub --version` (if used with JupyterHub)
4.1.6

### `jupyter notebook --version` 
7.2.1

### Expected behavior
Forgrader to load

### Actual behavior
Formgrader not loading 
and
console Error:
Refused to frame 'mydomain.com' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

### Steps to reproduce the behavior
Install TLJH
Install nbgrader
Load formgrader

**Comment by brichet** [comment] 2024-08-03 12:55
@henry-goluss you may find an answer in https://github.com/jupyter/nbgrader/issues/1870

**Comment by henry-goluss** [comment] 2024-08-03 13:05
Same behavior indeed. Thanks you, I will post my future messages there.

**Comment by brichet** [comment] 2024-08-03 15:29
Closing as duplicate of https://github.com/jupyter/nbgrader/issues/1870

**Closed** 2024-08-03 15:30 UTC
Labels: bug
