### ISSUE TITLE
Notebooks for manual grading are not rendered properly

### ISSUE THREAD

**Issue by javoha** [jupyter/nbgrader#1087] opened 2019-05-15 12:46 UTC
Hello and thanks for creating nbgrader. I am new to it and hope you can help me with the following problem.

### Operating system
Windows 10

### `nbgrader --version`
0.5.5

### `jupyterhub --version` (if used with JupyterHub)
not used on jupyterhub

### `jupyter notebook --version` 
5.7.8

### Expected behavior
Rendered notebooks in manual grading should be displayed properly (Cells stacked vertically, as in the original notebooks).

### Actual behavior
Rendered notebooks in manual grading are displayed distorted (Cells stack horizontally and text behaves equally weird) - see screenshot

### Steps to reproduce the behavior
After using autograde on students assignments (which was possible only after downgrading SQLAlchemy to version 1.2.18 as described in this issue: https://github.com/jupyter/nbgrader/issues/1073#issuecomment-489978804) the resulting rendered versions for the manual grading looks very off (screenshot).

Thanks alot for any advice.

![Screenshot_2019-05-15 assignment1](https://user-images.githubusercontent.com/38279459/57776244-45c8f480-771f-11e9-8385-8856fd35498c.png)

**Comment by jhamrick** [comment] 2019-05-21 20:22
Hmm, very strange. Unfortunately I'm not able to reproduce this so will need a bit more information to try to track this down:

1. Could you try using the version of nbgrader on master and see if it is still a problem?
2. If not, can you run `jupyter nbconvert --version` and paste the output here?
3. Also, what browser are you using? Can you try a different browser and let me know if it's a problem there too?

**Comment by Sefriol** [comment] 2019-05-21 20:58
We are currently running a Machine Learning course were this actually happens too. For us, we can also see the same rendering error for instructor version in Github, so it might not be an uncommon problem. 

Do you also see this rendering error in Github @javoha ?

Currently we have just distributed the feedback for this round, but I'm unsure how much of the notebook we are going to reuse next year, I can send you the notebook in privite for the time being for further inspections.

Though in general, nbconvert errors are not uncommon. It probably has to do with Latex / Markdown within the notebook itself that causes it to break. I haven't had the time to fully investigate this.

**Comment by jhamrick** [comment] 2019-05-21 21:04
Yeah, I suspect the problem may lie with nbconvert rather than nbgrader itself.

It sounds like you are seeing this for some notebooks but not others (based on your comment about it being the notebook comments causing the issue)? If so, then having a notebook that causes the problem would be very useful indeed!

**Comment by Sefriol** [comment] 2019-05-21 21:49
@jhamrick I'll shared the repository for you, for now.

https://github.com/Sefriol/MOOC-ML/blob/master/source/R2_Regression/Round%202%20-%20Regression.ipynb

Here you can see the error in Github. Same can be seen in the feedback form / manual grading part.

**Comment by javoha** [comment] 2019-05-22 07:50
@jhamrick Thanks for looking into it.

The nbconverter version is `5.4.1`. I tried it in Mozilla Firefox and Google Chrome, both showed the same result. I will check if using the nbgrader master version behaves differently.

**Comment by Sefriol** [comment] 2019-05-24 10:53
For our notebooks I might have found the reason why this occurs:

We use some html-div tags in your markdown cells to make some sections format correctly when you view them in Jupyter. It seems that nbconvert won't interpret these modifications in the same way and causes `<div class="cell border-box-sizing code_cell rendered"/>` to be rendered within each other, causing them to go sideways.

It was gone unnoticed since code/feedback testing was in done in the first phase of notebook review and nbconvert issues didn't come up by then. Now that we later visually updated the notebooks, we didn't notice the change in nbconvert until this point.

**Comment by javoha** [comment] 2019-05-27 13:49
@Sefriol Very interesting and thanks for sharing. We also use stuff like `<div class="alert alert-warning">` in our assignments so I think this might be the issue. I know that the rendering worked half a year ago without problems though. 

How did you solve it in your case if the students version is already collected? Any suggestions?

Thanks again and have a nice week everyone.

**Comment by Sefriol** [comment] 2019-05-27 18:39
We found out that student feedback forms can be fixed by removing the markdown cells from the notebook. This can be done by using the standard config file for nbgrader:

```python
c = get_config()
c.Feedback.HTMLExporter.exclude_markdown=True
```
I haven't yet looked into manual grading, but there might be a similar solution for those as well.

Ofc, it's not the most ideal solution, but it might be the best one for the moment.

Other options could be just removing all divs from the submitted notebooks via a script.

**Comment by javoha** [comment] 2019-05-28 10:03
Thanks again for the ideas. I just deleted all `div classes` from one of the solutions and then it actually does render properly - problem detected. Regarding the solution though: Some of our markdown cells containing these warnings are "read-only" so we cannot delete the problematic parts in the versions the students handed in. Suggestions for other solutions are thus still very welcome.

**Comment by jhamrick** [comment] 2019-05-28 16:43
Thanks for sharing the notebook! I can indeed reproduce using the version of nbconvert installed with nbgrader (5.4.1). I tried testing on nbconvert master and actually get an error when trying to convert it to html, so I'll try to debug that and submit a fix to nbconvert proper. Then we can see if the original bug is fixed with nbconvert master or not!

**Comment by jhamrick** [comment] 2019-05-28 16:51
I fixed the unrelated issue (https://github.com/jupyter/nbconvert/pull/1036) and the problem remains. Thus this is indeed a problem with nbconvert and not nbgrader. I will open up a bug on the nbconvert repo to track it.

**Comment by jhamrick** [comment] 2019-05-28 17:16
I created https://github.com/jupyter/nbconvert/issues/1037 to track the issue. However, I'm not sure it's actually very straightforward to fix. I think the problem is (at least for the notebook @Sefriol sent me) that the `<div>` tags sometimes are not separated by a new line from the previous paragraph and are indented, e.g.

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    <div>
    
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div>
```

While this wouldn't be a problem for regular HTML, the fact that these are markdown cells complicates things. Can you try making sure that your `<div>` tags are always separated from the previous paragraph by a newline, and not indented? I think that should fix the problem for now (it seemed to at least for that notebook).

**Comment by Sefriol** [comment] 2019-05-28 17:36
Some cases when adding HTML-tags we encountered other rendering issues either in the Github preview, or in the notebook itself. Sometimes adding new lines fixed those issues, but other times it caused more rendering issues. And sometimes indenting fixed some others.

So yes. I assume this is a non-trivial issue to solve.

**Comment by jhamrick** [comment] 2019-05-30 14:30
I will go ahead and close this since it's not something we can deal with nbgrader specifically, but hopefully it will be addressed at some point in nbconvert.

**Closed by jhamrick** 2019-05-30 14:30 UTC
Labels: bug

**Comment by reinimaurer1** [comment] 2020-11-11 17:55
This has been closed for a while, but I just wanted to add that I only get the rendering issue with <div> statements if those statements aren't properly closed with </div>
All the bootstrap coloring flags work fine and render normally, for example 
<div class="alert alert-block alert-info">  TEXT </div>

I am testing this on the current nbgrader master.
