### ISSUE TITLE
Hiding autograder test code cells in feedback but retaining their output

### ISSUE THREAD

**Issue by psychemedia** [jupyter/nbgrader#1156] opened 2019-06-12 00:17 UTC
Looking at the reports generated as feedback for students, I'm not so keen on showing students the code used to run the assessment tests, but I would like to retain feedback style outputs created from those tests:

<img width="864" alt="nbgrader_feedback" src="https://user-images.githubusercontent.com/82988/59314984-9b0d0d00-8caf-11e9-8185-ecf7e42cb95a.png">

Is there any way of doing this at the moment?

**Comment by jaspervdh96** [comment] 2019-06-14 12:51
There's no option in nbgrader afaik, but I change the feedback files myself:
> ## Hide the traceback (which includes parts of the hidden tests)
>         html = re.sub(
>             r'(<div class="output_subarea output_text output_error">\n<pre>\n)(?:(?!<\/div>)[\w\W])*(<span class="ansi-red-intense-fg ansi-bold">[\w\W]*?<\/pre>)',
>             r'\1\2',
>             html)
> ## Hide the hidden tests
>         html = re.sub(
>             r'<span class="c1">### BEGIN HIDDEN TESTS<\/span>[\w\W]*?<span class="c1">### END HIDDEN TESTS<\/span>',
>             '',
>             html)

**Comment by jhamrick** [comment] 2019-06-16 18:41
That's a nice workaround for now, thanks @jaspervdh96 !

This is a duplicate of #917 so I am going to close it, though I'll leave a note in the other issue about the question of whether to keep the cell output or not. I think it might be hard to determine which output is a result of a hidden test and which is not, so I think maybe the easiest way to implement this anyways is to strip out the hidden tests from the code cell but retain all cell output.

**Closed by jhamrick** 2019-06-16 18:41 UTC

**Comment by jhamrick** [comment] 2019-06-16 18:46
I should add that another workaround you can use if you just want to reduce the amount of code that's in the test cell, you could put the tests in a separate file that you release with the notebook, then just have something like the following in the test cell:

```
import tests
tests.test_1()
```

**Comment by lwasser** [comment] 2020-09-30 16:57
we have actually implemented the scrub html in our abc-classroom tool (which works with github classroom and we use nbgrader). pr here - https://github.com/earthlab/abc-classroom/pull/291 thank you - @jaspervdh96 we actually used your code to implement this in our tool!! i would be happy to cite you in the code however you'd like to see attribution handled :) regex works great for this purpose.

**Comment by papalotis** [comment] 2020-12-01 15:38
I just want to point out that @jaspervanderheide 's solution doesn't remove the traceback anymore.  I haven't tried to figure out what part of the regex doesn't match any more but I use a bs4 solution which I find much more readable
```python
soup = BeautifulSoup(html_content, features="html.parser")
# remove tracebacks
for div in soup.find_all(
    "div", {"class": "output_subarea output_text output_error"}
):
    div.decompose()

html_no_traceback = str(soup)
```
