### ISSUE TITLE
schema and task meta-data not being dealt with properly via update

### ISSUE THREAD

**Issue by ttimbers** [jupyter/nbgrader#1086] opened 2019-05-13 22:48 UTC
I am using the following versions of things:

```
Python version 3.6.5 |Anaconda custom (64-bit)| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
nbgrader version 0.6.0.dev
```

And when I run `nbgrader validate NOTEBOOK` I get an error, with a useful error message that suggests I run `nbgrader update NOTEBOOK`. However, when I run that, I get a not very helpful error message:

```
[UpdateApp | INFO] Updating metadata for notebook: source/worksheet_06/worksheet_06.ipynb
Traceback (most recent call last):
  File "/Users/timberst/anaconda3/bin/nbgrader", line 11, in <module>
    sys.exit(main())
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/apps/nbgraderapp.py", line 301, in main
    NbGraderApp.launch_instance()
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/apps/nbgraderapp.py", line 294, in start
    super(NbGraderApp, self).start()
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/apps/updateapp.py", line 81, in start
    write(nb, notebook)
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/v2.py", line 113, in write_v2
    MetadataValidatorV2().validate_nb(nb)
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/v2.py", line 85, in validate_nb
    super(MetadataValidatorV2, self).validate_nb(nb)
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/common.py", line 50, in validate_nb
    self.validate_cell(cell)
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/v2.py", line 46, in validate_cell
    super(MetadataValidatorV2, self).validate_cell(cell)
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/common.py", line 45, in validate_cell
    schema, SCHEMA_VERSION)
nbgrader.nbgraderformat.common.SchemaMismatchError: outdated schema version: 3 (expected 2)

```

I'm a bit stuck. I'd be happy if I could even strip the meta-data and recreate the assignment (although updating the meta data would be a better option). Currently, all I have been able to do is manually copy the cell contents into a new notebook. The notebook I am trying to update was created on an older version of nbgrader...

**Comment by ttimbers** [comment] 2019-05-13 22:48
This is one example of a "broken" notebook: 

[worksheet_08.zip](https://github.com/jupyter/nbgrader/files/3175040/worksheet_08.zip)

**Comment by ttimbers** [comment] 2019-05-13 22:49
I can confirm that using find and replace to change the schema version from 3 to 2 manually fixes the problem...

Another weird meta-data issue is that if I try to solve the problem that way, I then get this error:

```
[UpdateApp | ERROR] Traceback (most recent call last):
      File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/apps/updateapp.py", line 81, in start
        write(nb, notebook)
      File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/v2.py", line 113, in write_v2
        MetadataValidatorV2().validate_nb(nb)
      File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/v2.py", line 85, in validate_nb
        super(MetadataValidatorV2, self).validate_nb(nb)
      File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/common.py", line 50, in validate_nb
        self.validate_cell(cell)
      File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/v2.py", line 46, in validate_cell
        super(MetadataValidatorV2, self).validate_cell(cell)
      File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/common.py", line 46, in validate_cell
        jsonschema.validate(cell.metadata['nbgrader'], self.schema)
      File "/Users/timberst/anaconda3/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
        cls(schema, *args, **kwargs).validate(instance)
      File "/Users/timberst/anaconda3/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
        raise error
    jsonschema.exceptions.ValidationError: Additional properties are not allowed ('task' was unexpected)
    
    Failed validating 'additionalProperties' in schema:
        {'$schema': 'http://json-schema.org/draft-04/schema#',
         'additionalProperties': False,
         'properties': {'cell_type': {'description': 'the type the cell was '
                                                     'when nbgrader assign was '
                                                     'run; used for checking '
                                                     'if the cell type has '
                                                     'changed and should only '
                                                     'be present in the '
                                                     'student version of an '
                                                     'assignment',
                                      'enum': ['raw', 'code', 'markdown'],
                                      'type': 'string'},
                        'checksum': {'description': 'a checksum of the cell '
                                                    'contents; generally only '
                                                    'present in the student '
                                                    'version of an assignment',
                                     'maxLength': 32,
                                     'minLength': 32,
                                     'type': 'string'},
                        'grade': {'default': False,
                                  'description': 'whether this cell should be '
                                                 'graded',
                                  'type': 'boolean'},
                        'grade_id': {'description': 'the nbgrader id of the '
                                                    'cell, only present if one '
                                                    'or more of '
                                                    'grade/locked/solution is '
                                                    'true',
                                     'pattern': '^[a-zA-Z0-9_\\-]*$',
                                     'type': 'string'},
                        'locked': {'default': False,
                                   'description': 'whether the cell should be '
                                                  'editable',
                                   'type': 'boolean'},
                        'points': {'description': 'the number of points this '
                                                  'cell is worth; only present '
                                                  'if grade is true',
                                   'minimum': 0,
                                   'type': 'number'},
                        'schema_version': {'description': 'the version of the '
                                                          'cell metadata '
                                                          'schema',
                                           'maximum': 2,
                                           'minimum': 2,
                                           'type': 'integer'},
                        'solution': {'default': False,
                                     'description': 'whether this cell '
                                                    'contains a solution',
                                     'type': 'boolean'}},
         'required': ['schema_version', 'grade', 'locked', 'solution'],
         'title': 'nbgrader cell metadata schema',
         'type': 'object'}
    
    On instance:
        {'grade': False,
         'grade_id': 'cell-6093d584be2ad9ed',
         'locked': True,
         'schema_version': 2,
         'solution': False,
         'task': False}
```

Which I can then solve by deleting all lines that have `'task': False` in them (while at the same time keeping the JSON formatting).

*note - the above was copied over from #883*

**Comment by jhamrick** [comment] 2019-05-13 23:24
Thanks for opening the new issue! I'll try to have a look at this in the next few days.

**Comment by jhamrick** [comment] 2019-05-21 21:17
Hmm, I can't seem to replicate the issue with this particular notebook---is it possible you sent me the version after you had fixed the metadata manually?

```
(nbgrader-R) [jhamrick@lyra]:/tmp/course101
$ nbgrader validate source/worksheet_08/worksheet_08.ipynb
[ValidateApp | INFO] Validating '/private/tmp/course101/source/worksheet_08/worksheet_08.ipynb'
> IRkernel::main()
[ValidateApp | INFO] Executing notebook with kernel: ir
Success! Your notebook passes all the tests.
```

Otherwise, it sounds like potentially what is happening is that you created the notebook using a newer version of nbgrader and are now trying to validate it with a slightly older version of nbgrader, since it's complaining about the nbgrader format being too new (`outdated schema version: 3 (expected 2)`).

Can you run `nbgrader --version` and paste the output here?

**Comment by jhamrick** [comment] 2019-05-21 21:20
Oh, I guess you did already provide the nbgrader version (0.6.0.dev), so nevermind about that question.

It does sound to me though like you're somehow using two different versions. Can you try ensuring that you've upgraded nbgrader to the most recent version on master?

**Comment by ttimbers** [comment] 2019-05-23 16:34
Yes, I am using nbgrader version (0.6.0.dev)... Now we have moved to developing in a container, and using that same container for grading, but I think it would still be good in general to have nbgrader to either be more robust when updating, and/or have a function that strips a old nbgrader version notebook of all nbgrader meta-data so that it can be converted manually to a more recent version (obviously the former is better for users).

**Comment by jhamrick** [comment] 2019-05-23 17:05
Based on the error message you got, I think the issue is the other way around: you were trying to validate a notebook that had a newer version (version 3) than what nbgrader knew how to deal with (version 2). There's unfortunately not a good way to have older versions of nbgrader know what to do with newer versions, but I could modify the error message informing the user they need to upgrade their version of nbgrader to be able to read the notebook.

**Comment by ttimbers** [comment] 2019-05-23 17:32
But I do not understand how I would have generated that error message if the machine I ran `nbgrader update NOTEBOOK` on returns:

```
Python version 3.6.5 |Anaconda custom (64-bit)| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
nbgrader version 0.6.0.dev
```
from `nbgrader --version`...

**Comment by jhamrick** [comment] 2019-05-23 17:40
The PR which updated the nbgrader format from 2 to 3 happened during the
0.6.0 development cycle (which is still ongoing), so my guess is that you
installed the master version of nbgrader before that PR was merged. So your
version would be 0.6.0.dev but the version after the PR was merged is also
0.6.0.dev. Unfortunately the version number doesn't specify the exact
commit from which you installed nbgrader so I can't say for sure, but
that's at least my suspicion.

**Comment by jhamrick** [comment] 2019-08-24 23:30
I am closing this issue because there hasn't been any activity on it in a while. However, if you (or others) continue to encounter problems, feel free to comment here or open a new issue!

**Closed by jhamrick** 2019-08-24 23:30 UTC
Labels: bug, needs info
