### ISSUE TITLE
The header file is not åäö-friendly

### ISSUE THREAD

**Issue by consideRatio** [jupyter/nbgrader#902] opened 2017-10-23 11:50 UTC
### Operating system
Windows 10

### `nbgrader --version`
0.5.3

### `jupyter --version`
4.3.0

### Expected behavior
Generation of student notebooks should concatenate the content of the header file with the notebook without any issues with special letters such as å ä and ö.

### Actual behavior
The student versions's header gets its å ä and ö characters misrepresented.

### Steps to reproduce the behavior
Create a header file with the characters å ä and ö and release a student version, look at the student version and conclude that the header does not look like it should in the released student version.

**Comment by jhamrick** [comment] 2017-10-28 10:44
Hmm, I am unfortunately not able to reproduce it. Could you send me copies of notebooks that lead to this bug happening? Additionally, could you give me the output of:

```
jupyter nbconvert --version
```

and

```
jupyter notebook --version
```

Thanks!

**Comment by jhamrick** [comment] 2017-10-28 10:46
Also, if you could send me a copy of the notebook that isn't formatted correctly, that would be helpful, too!

**Comment by consideRatio** [comment] 2017-10-28 15:00
@jhamrick thanks for looking into the issue!

I tried to reproduce it myself on a Ubuntu computer without success, then I used a windows 10 computer with exactly the same versions of jupyter, jupyter notebook, nbgrader, nbconvert, python and conda, and was able to reproduce it!

https://github.com/consideRatio/nbgrader-issues

![image](https://user-images.githubusercontent.com/3837114/32135552-6a2844a0-bc01-11e7-91a2-125c46d1bb4f.png)

**Comment by jhamrick** [comment] 2017-10-28 19:13
Hmm, this sounds like it might be a windows issue, then. I unfortunately don't currently have access to a windows machine to test this (and won't for probably at least another month---I just moved to the UK and my windows machine is still in a shipping container somewhere)... @lgpage would you be able to see if you can reproduce the bug on windows?

@consideRatio if you're able to do a bit more investigating on your own, here are a few suggestions. I suspect the issue probably lies in this file which is where the header is concatenated: https://github.com/jupyter/nbgrader/blob/master/nbgrader/preprocessors/headerfooter.py My initial suspicion is maybe that when the header/footer notebook is read (lines 23 & 32) it doesn't read the notebook in with the correct encoding. I would try replacing those lines so they use a signature like the one that nbconvert uses, such as here: https://github.com/jupyter/nbconvert/blob/master/nbconvert/exporters/exporter.py#L173 I am not totally sure that will fix the problem, but it is my first guess since the encoding seems to be preserved when nbgrader uses the underlying nbconvert machinery, but not when it opens the notebooks itself.

**Comment by jhamrick** [comment] 2017-10-29 19:41
Closed by #906

**Closed by jhamrick** 2017-10-29 19:41 UTC
Labels: bug
