### ISSUE TITLE
Allow autograde tests to be hidden from students

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#476] opened 2016-04-01 14:59 UTC
For really simple problems, showing the students the assert tests, gives away the answer. It would be really helpful if an instructor could write assert tests, but have them hidden from the student. Not sure how that would work exactly. @dlsun

**Comment by jhamrick** [comment] 2016-04-01 15:42
Yes, definitely agree, though this is a duplicate of #390 so I will close this to track the issue there.

**Closed by jhamrick** 2016-04-01 15:42 UTC
Labels: duplicate
