### ISSUE TITLE
Accessing scores per question from assignments

### ISSUE THREAD

**Issue by TomDonoghue** [jupyter/nbgrader#938] opened 2018-03-01 01:54 UTC
First, a question: Is there a way to export grades, or interact with the gradebook so as to get the grades per assignment, per question? 

As far as I can tell, there is not (although perhaps possible with a custom Exporter?). 

Unless I've missed something that would currently make this possible, I think this might be a useful feature:
- It would allow for better auditing of assignments, seeing where students are having trouble, tracking problem topics, and individual outlier questions (that suggests a problem with the Q).
- It would also be useful to deal grading quirks: it would be easier to recalculate total assignment scores including or excluding certain questions, if issues arise (I have this issue right now in which a bad test case can sometimes fail, and I can't find a clear way to exclude this question from the overall grades).

Perhaps there is something in the underlying grading that makes this type of logging / exporting difficult, but if anyone knows a suggested way to do this, I would like to try it.

**Comment by jhamrick** [comment] 2018-03-01 04:58
Yes, this is definitely something we plan to add, see #799

In the meantime though this should be pretty straightforward to do yourself by writing a [custom exporter](http://nbgrader.readthedocs.io/en/stable/plugins/export-plugin.html). Here is a more detailed example of how to [extract information from the gradebook](http://nbgrader.readthedocs.io/en/stable/user_guide/advanced.html#getting-information-from-db). You can combine these two examples by essentially taking the code from the latter link and putting it in the `export` method of the plugin.

And, in particular, if you want to compute things like the average score per assignment per question there are a lot of methods the gradebook object supports for doing things like this. For example, there is [`average_notebook_score`](http://nbgrader.readthedocs.io/en/stable/api/gradebook.html#nbgrader.api.Gradebook.average_notebook_score) which gives the average score for a notebook in an assignment. See here for a full list of all gradebook functions: http://nbgrader.readthedocs.io/en/stable/api/gradebook.html

There isn't a good way for excluding particular questions from overall grades, and this is likely something we will not support officially in nbgrader---but it is again something you could write a custom exporter for (though you'd have to loop over all cells and compute the total score manually, rather than using a predefined gradebook method).

**Comment by jhamrick** [comment] 2018-05-03 22:46
I am going to close this issue as it is a duplicate---if there are any further questions please comment on #799 so we can track them there!

**Closed by jhamrick** 2018-05-03 22:46 UTC
Labels: duplicate

**Comment by TomDonoghue** [comment] 2018-05-05 18:36
@jhamrick :
Sorry - I forget to get back to you originally that yes, using a CustomExporter allowed me to do all the things I wanted / needed to do for our assignments! Thanks for the guidance!

More broadly: also huge thank-you to you (and others) for all your work on nbgrader - we just finished using it again for our large 'data science' class, and I'm really not sure how we could have gone about running that class without nbgrader, which has worked wonderfully!

**Comment by jhamrick** [comment] 2018-05-06 16:03
Glad to hear you were able to get it all working with a custom exporter! And even more glad to hear that it's been working out so well for your data science class 😄

**Comment by rubdos** [comment] 2021-06-24 16:08
@TomDonoghue originally asked a per-question export, which I don't think #799 does. I've written a quick custom exporter here that does this: https://gist.github.com/rubdos/fac49824301ee1fc0a14513e0d127956

**Comment by Adamtaranto** [comment] 2022-11-15 03:31
> @TomDonoghue originally asked a per-question export, which I don't think #799 does. I've written a quick custom exporter here that does this: https://gist.github.com/rubdos/fac49824301ee1fc0a14513e0d127956

@rubdos, How do you use this class? Does it need to be inserted into the nbgrader source somewhere?

**Comment by rubdos** [comment] 2022-11-15 12:52
I have this in my bash history on JupyterLab. It's been a while since I've used it...

```
nbgrader export --exporter=vubexporter.VubExporter
```

I seem to have saved the file in the directory where I run the nbgrader export command.

**Comment by Adamtaranto** [comment] 2022-12-04 22:32
@rubdos - Thanks Ruben, I gave it a go but it doesn't seem to get along with the current version of nbgrader or perhaps just not with my assignment database. I'm manually adding submissions to the `submitted` directory so they don't have timestamps, which may be causing some of the issue.

**Comment by Adamtaranto** [comment] 2022-12-05 06:58
Here is my custom exporter for getting grades per question: https://gist.github.com/Adamtaranto/91e1fb1f91b274fd093c14a0c10405ca

It supports the --student and --assignment flags, returns blank records for null submissions, and reports for all graded cell types.

@jhamrick - I don't think this is a duplicate of #799. It would be great to have an 'export scores per question' option ship with nbgrader.
