### ISSUE TITLE
Links and validate buttons don't work in the assignment list UI

### ISSUE THREAD

**Issue by r96941046** [jupyter/nbgrader#1076] opened 2019-03-20 10:09 UTC
### Operating system
Ubuntu 16.04.5 LTS

### `nbgrader --version`
0.5.4

### `jupyterhub --version` (if used with JupyterHub)
0.9.4

### `jupyter notebook --version` 
5.5.0

### Expected behavior
When accessing notebooks in fetched assignment from the assignment list, user should be directed to the notebook. User should be able to validate notebooks using the validate button in the assignment list UI.

### Actual behavior
Links for notebooks under assignment list are invalid and show 404 not found. The validate buttons after them aren't working either.

### Steps to reproduce the behavior
Using jupyterhub with nbgrader, having `c.Spawner.notebook_dir = '~/<CourseName>'` in `jupyterhub_config.py` and `c.CourseDirectory.root = '/home/<Username>/<CourseName>'` in `nbgrader_config.py`. No problem for instructors to create releases and assign them; however, after students fetch those assignments through assignment_list UI, those notebook hyperlinks in the UI don't work properly. The validate button under assignment_list UI does not work either, which prints out the following error.

```
Traceback (most recent call last):
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/nbgrader/server_extensions/validate_assignment/handlers.py", line 48, in validate_notebook
    result = validator.validate(os.path.join(self.notebook_dir, path))
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/nbgrader/validator.py", line 227, in validate
    with utils.chdir(dirname):
  File "/data/anaconda/envs/py35/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/nbgrader/utils.py", line 228, in chdir
    os.chdir(dirname)
FileNotFoundError: [Errno 2] No such file or directory: '/home/<Username>/<CourseName>/../../../data/home/<Username>/<CourseName>/ps1'
```

Students can still work on answers in the notebooks from under jupyter 'Files' tab, and can still submit those notebooks to the shared exchange folder. Just the links in UI don't work.

**Comment by jhamrick** [comment] 2019-05-12 17:19
Hmm, unfortunately I'm not able to replicate this with the information you've provided---could you provide some more detailed steps to reproduce the problem (including the exact contents of the nbgrader_config.py files?)

**Comment by jhamrick** [comment] 2019-08-24 23:18
I am closing this issue because there hasn't been any activity on it in a while. However, if you (or others) continue to encounter problems, feel free to comment here or open a new issue!

**Closed by jhamrick** 2019-08-24 23:18 UTC
Labels: needs info, question
