### ISSUE TITLE
db_assignments and db_students not recognized by ExchangeRelease

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [jupyter/nbgrader#727] opened 2017-03-23 12:12 UTC
When I run `nbgrader release ps1` for the nbgrader example I get:

    [ReleaseApp | WARNING] Config option `db_assignments` not recognized by `ExchangeRelease`.
    [ReleaseApp | WARNING] Config option `db_students` not recognized by `ExchangeRelease`.

My config looks like this:

    from nbgrader.utils import get_username

    c = get_config()

    c.Exchange.course_id = "demo"
    c.Exchange.db_assignments = [dict(name="ps1")]
    c.Exchange.db_students = [dict(id=get_username())]
    c.Exchange.root = "/home/user/dev/nbgrader/exchange/"

What does that mean? Should I create some database? The Readme does not tell me to do so at: https://github.com/jhamrick/nbgrader-demo

**Comment by jhamrick** [comment] 2017-03-23 16:54
You are getting that error because those are not config options for the `Exchange` class. Did you put those options in your config file because you saw them somewhere in the documentation? (If so, that's incorrect, and so I'd like to fix it). 

Anyway, to fix the issue, you should specify those options under the `NbGrader` object, i.e. `c.NbGrader.db_assignments` and `c.NbGrader.db_students`.

**Comment by ZelphirKaltstahl** [comment] 2017-03-23 22:30
@jhamrick That's what I had at first. Then it told me using `NbGrader` was deprecated and to use `Exchange` instead. Maybe not all uses of `NbGrader` are deprecated yet?

**Comment by jhamrick** [comment] 2017-03-23 23:20
Can you use your old config and paste the exact message it gave you when it told you `NbGrader` was deprecated? (I can't reproduce it -- I find it says so for the `course_id` option, but not `db_assignments` or `db_students`.)

**Comment by jhamrick** [comment] 2017-05-03 22:39
I am going to close this as this issue is more than a month old, but let me know if there are still issues here.

**Closed by jhamrick** 2017-05-03 22:39 UTC
Labels: question

**Comment by ZelphirKaltstahl** [comment] 2017-05-04 00:14
@jhamrick Wont the issue be forgotten, if the issue is closed? Shouldn't it rather be closed when it's fixed? Just wondering.
I totally forgot about this issue. I already had to pursue another way of doing things, but I guess it would be great to have a fix, if it is really a bug.

**Comment by jhamrick** [comment] 2017-05-04 01:13
Well, as I mentioned it's not a bug that `db_students` and `db_assignments` aren't recognized by `ExchangeRelease` because those are config options for `NbGrader`. You said that the deprecation warning told you `NbGrader` was deprecated, but as far as I can tell from grepping the source there is no  such error message (there is one that says `use Exchange.course_id rather than NbGrader.course_id`, but that is specifically about `course_id` and not `NbGrader` in general). So to me this doesn't seem like a bug -- though if you can show me that it is, I am happy to reopen the issue!
