### ISSUE TITLE
Older assignments fail validation in new nbgrader

### ISSUE THREAD

**Issue by dsblank** [jupyter/nbgrader#883] opened 2017-08-31 19:56 UTC
Attempting to use an assignment (from a few months ago), it fails validation because it is lacking:

```
   "schema_version": 1,
```

in the JSON for each grading cell. Manually adding that appears to make nbgrader happy. Why can't the system just add that by default?

**Comment by lgpage** [comment] 2017-09-01 12:37
@dsblank does the update command also fail?
```bash
nbgrader update path/to/assignment
```

**Comment by dsblank** [comment] 2017-09-01 12:41
I didn't know about that at the time. But I think that that is orthogonal to the question: why not fix it (or at least suggest that the user run "update") rather than raising an exception?

**Comment by lgpage** [comment] 2017-09-01 13:05
I agree, was just curious.

**Comment by dsblank** [comment] 2017-09-01 14:19
I did run `nbgrader update` on a similar notebook, and it reported that it was "Updating metadata for notebook". Upon inspection, it appears that it did add the schema_version to cell metadata. So, all is working as designed, it's just that the design could allow for auto-updating.

**Comment by lgpage** [comment] 2017-09-01 14:37
I also get the same behaviour (validation failure) from create an assignment from a completely new Notebook and then trying to assign it. An "auto-updating" work flow would be better.

**Comment by jhamrick** [comment] 2017-10-18 19:22
[Catching up on issues and PRs as I've been away for the last two months]

@dsblank The error message should include instructions to run nbgrader update, e.g. I see:

```
[AssignApp | ERROR] Notebook failed to validate. Please update the metadata with `nbgrader update`.
[AssignApp | ERROR] There was an error processing assignment: /private/tmp/course101/source/./ps1
[AssignApp | ERROR] Traceback (most recent call last):
      File "/Users/jhamrick/miniconda3/lib/python3.5/site-packages/nbgrader/converters/base.py", line 293, in convert_notebooks
        self.convert_single_notebook(notebook_filename)
      File "/Users/jhamrick/miniconda3/lib/python3.5/site-packages/nbgrader/converters/base.py", line 249, in convert_single_notebook
        output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
      File "/Users/jhamrick/miniconda3/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 172, in from_filename
        return self.from_file(f, resources=resources, **kw)
      File "/Users/jhamrick/miniconda3/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 190, in from_file
        return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
      File "/Users/jhamrick/miniconda3/lib/python3.5/site-packages/nbconvert/exporters/notebook.py", line 31, in from_notebook_node
        nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
      File "/Users/jhamrick/miniconda3/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 132, in from_notebook_node
        nb_copy, resources = self._preprocess(nb_copy, resources)
      File "/Users/jhamrick/miniconda3/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 309, in _preprocess
        nbc, resc = preprocessor(nbc, resc)
      File "/Users/jhamrick/miniconda3/lib/python3.5/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
        return self.preprocess(nb,resources)
      File "/Users/jhamrick/miniconda3/lib/python3.5/site-packages/nbgrader/preprocessors/checkcellmetadata.py", line 16, in preprocess
        raise ValidationError(msg)
    jsonschema.exceptions.ValidationError: Notebook failed to validate. Please update the metadata with `nbgrader update`.

[AssignApp | WARNING] Removing failed assignment: /private/tmp/course101/release/ps1
[AssignApp | ERROR] There was an error processing assignment 'ps1' for student '.'
[AssignApp | ERROR] Please see the error log (.nbgrader.log) for details on the specific errors on the above failures.
```

Did you see a different error? If so, I'd definitely like to update it so that it reports that `nbgrader update` should be used. If not, would it be helpful to make the error a bit more verbose? For example, something along the lines of "It looks like you're using an old version of an nbgrader assignment. To use nbgrader with this assignment, you should back up your copy of the assignment and then run the `nbgrader update` command."

@lgpage I can't seem to reproduce the validation error from a completely new notebook. Is the notebook completely empty, or does it have some other stuff in it?

**Comment by jhamrick** [comment] 2017-10-29 21:14
Ok, regarding the original issue, I've tried to make error messages about the schema version a bit friendlier in #908 and #909. For example, the create assignment extension will give a pop-up message if the schema version is old:

![image](https://user-images.githubusercontent.com/83444/32148234-b0af7336-bceb-11e7-8191-4a2ea6f15e1a.png)

Running the validate command (either through the browser or on the command line) will give more explicit instructions about what to do, e.g.:

![image](https://user-images.githubusercontent.com/83444/32148232-a4794cd6-bceb-11e7-9d89-76fef41a6c1f.png)

Running `nbgrader assign` from the formgrader:

![image](https://user-images.githubusercontent.com/83444/32148353-a404b0f4-bced-11e7-8a22-c327f6579bd7.png)

I definitely think it would be nice to be able to have the notebooks automatically update the metadata, but there are a few reasons I'm hesitant to add this:

1. There is not a good way to do this from the notebook interface without reimplementing all the schema handling functionality in javascript. The reason the native nbformat stuff works well is because the notebook version is updated before the notebook is sent to the browser, but in the case of nbgrader, there is no way to do this until after the notebook reaches the browser. I could create a server route that updates the notebook on disk, but this would then require the user to refresh the notebook page to get the update. If they do not refresh, this could potentially cause further confusion with getting errors like "the notebook has been updated on disk, do you want to overwrite it or refresh?"
2. I am worried about automatically updating metadata in the rare case that it somehow breaks someones assignment. That's why all the error messages tell the user to back up their notebooks first before updating the metadata.

**Comment by jhamrick** [comment] 2018-05-08 21:58
I am closing this issue because there hasn't been any activity on it in a while. However, if you (or others) continue to encounter problems, feel free to comment here or open a new issue!

**Closed by jhamrick** 2018-05-08 21:58 UTC
Labels: enhancement, needs info

**Comment by ttimbers** [comment] 2019-02-04 23:18
I am using the following versions of things:

```
Python version 3.6.5 |Anaconda custom (64-bit)| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
nbgrader version 0.6.0.dev
```

And when I run `nbgrader validate NOTEBOOK` I get an error, with a useful error message that suggests I run `nbgrader update NOTEBOOK`. However, when I run that, I get a not very helpful error message:

```
[UpdateApp | INFO] Updating metadata for notebook: source/worksheet_06/worksheet_06.ipynb
Traceback (most recent call last):
  File "/Users/timberst/anaconda3/bin/nbgrader", line 11, in <module>
    sys.exit(main())
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/apps/nbgraderapp.py", line 301, in main
    NbGraderApp.launch_instance()
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/apps/nbgraderapp.py", line 294, in start
    super(NbGraderApp, self).start()
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/apps/updateapp.py", line 81, in start
    write(nb, notebook)
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/v2.py", line 113, in write_v2
    MetadataValidatorV2().validate_nb(nb)
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/v2.py", line 85, in validate_nb
    super(MetadataValidatorV2, self).validate_nb(nb)
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/common.py", line 50, in validate_nb
    self.validate_cell(cell)
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/v2.py", line 46, in validate_cell
    super(MetadataValidatorV2, self).validate_cell(cell)
  File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/common.py", line 45, in validate_cell
    schema, SCHEMA_VERSION)
nbgrader.nbgraderformat.common.SchemaMismatchError: outdated schema version: 3 (expected 2)

```

I'm a bit stuck. I'd be happy if I could even strip the meta-data and recreate the assignment (although updating the meta data would be a better option). Currently, all I have been able to do is manually copy the cell contents into a new notebook. The notebook I am trying to update was created on an older version of nbgrader...

**Comment by jhamrick** [comment] 2019-05-12 16:08
@ttimbers Would you mind opening a new issue for this problem, and attach a the notebook that's causing problems? That would help us be able to debug this further---thanks!

**Comment by ttimbers** [comment] 2019-05-13 22:17
This is one example: 

[worksheet_08.zip](https://github.com/jupyter/nbgrader/files/3175040/worksheet_08.zip)

**Comment by ttimbers** [comment] 2019-05-13 22:21
I can confirm that using find and replace to change the schema version from 3 to 2 manually fixes the problem...

Another weird meta-data issue is that if I try to solve the problem that way, I then get this error:

```
[UpdateApp | ERROR] Traceback (most recent call last):
      File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/apps/updateapp.py", line 81, in start
        write(nb, notebook)
      File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/v2.py", line 113, in write_v2
        MetadataValidatorV2().validate_nb(nb)
      File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/v2.py", line 85, in validate_nb
        super(MetadataValidatorV2, self).validate_nb(nb)
      File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/common.py", line 50, in validate_nb
        self.validate_cell(cell)
      File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/v2.py", line 46, in validate_cell
        super(MetadataValidatorV2, self).validate_cell(cell)
      File "/Users/timberst/anaconda3/lib/python3.6/site-packages/nbgrader/nbgraderformat/common.py", line 46, in validate_cell
        jsonschema.validate(cell.metadata['nbgrader'], self.schema)
      File "/Users/timberst/anaconda3/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
        cls(schema, *args, **kwargs).validate(instance)
      File "/Users/timberst/anaconda3/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
        raise error
    jsonschema.exceptions.ValidationError: Additional properties are not allowed ('task' was unexpected)
    
    Failed validating 'additionalProperties' in schema:
        {'$schema': 'http://json-schema.org/draft-04/schema#',
         'additionalProperties': False,
         'properties': {'cell_type': {'description': 'the type the cell was '
                                                     'when nbgrader assign was '
                                                     'run; used for checking '
                                                     'if the cell type has '
                                                     'changed and should only '
                                                     'be present in the '
                                                     'student version of an '
                                                     'assignment',
                                      'enum': ['raw', 'code', 'markdown'],
                                      'type': 'string'},
                        'checksum': {'description': 'a checksum of the cell '
                                                    'contents; generally only '
                                                    'present in the student '
                                                    'version of an assignment',
                                     'maxLength': 32,
                                     'minLength': 32,
                                     'type': 'string'},
                        'grade': {'default': False,
                                  'description': 'whether this cell should be '
                                                 'graded',
                                  'type': 'boolean'},
                        'grade_id': {'description': 'the nbgrader id of the '
                                                    'cell, only present if one '
                                                    'or more of '
                                                    'grade/locked/solution is '
                                                    'true',
                                     'pattern': '^[a-zA-Z0-9_\\-]*$',
                                     'type': 'string'},
                        'locked': {'default': False,
                                   'description': 'whether the cell should be '
                                                  'editable',
                                   'type': 'boolean'},
                        'points': {'description': 'the number of points this '
                                                  'cell is worth; only present '
                                                  'if grade is true',
                                   'minimum': 0,
                                   'type': 'number'},
                        'schema_version': {'description': 'the version of the '
                                                          'cell metadata '
                                                          'schema',
                                           'maximum': 2,
                                           'minimum': 2,
                                           'type': 'integer'},
                        'solution': {'default': False,
                                     'description': 'whether this cell '
                                                    'contains a solution',
                                     'type': 'boolean'}},
         'required': ['schema_version', 'grade', 'locked', 'solution'],
         'title': 'nbgrader cell metadata schema',
         'type': 'object'}
    
    On instance:
        {'grade': False,
         'grade_id': 'cell-6093d584be2ad9ed',
         'locked': True,
         'schema_version': 2,
         'solution': False,
         'task': False}
```

Which I can then solve by deleting all lines that have `'task': False` in them (while at the same time keeping the JSON formatting).

**Comment by jhamrick** [comment] 2019-05-13 22:25
Ah thanks, this helps a lot! I think this is a separate issue than this one we're discussing on, and was introduced by a recent change (possibly #984 but I need to investigate more). Can you open a new issue thread to track this?

**Comment by ttimbers** [comment] 2019-05-13 22:49
ok, opened #1086

**Comment by jhamrick** [comment] 2019-05-13 23:22
Thanks!
