### ISSUE TITLE
Mathematics Display in `formgrade` giving `Math Processing Error`

### ISSUE THREAD

**Issue by mandli** [jupyter/nbgrader#426] opened 2015-11-18 21:39 UTC
We have noticed after upgrading to Mac OS X 10.11 that the `nbgrader formgrade` server has not been displaying mathematics correctly anymore displaying a `Math Processing Error` instead even though the notebooks themselves render appropriately and the `formgrade` server also renders correctly on previous versions of OS X.  The real problem is that the LaTeX itself is not viewable at all in the `formgrade` interface and we have to dig around and find the original document to grade.

My best guess right now is this is due to the move of the LaTeX installation after the newly implemented security protections in the new version of OS X.  Some of the issues are mentioned [here](https://www.tug.org/mactex/elcapitan.html) but I am not sure how to correct these.  Even a work around at this point would be helpful (we try to ensure that the students write an ID on the notebook but they, of course, forget occasionally).

**Comment by jhamrick** [comment] 2015-11-18 22:08
Hmm, the formgrader uses MathJax, which is purely javascript, so it shouldn't depend on the system installation of LaTeX. Could you let me know what version of the notebook you have (`jupyter notebook --version`)?

**Comment by mandli** [comment] 2015-11-19 12:51
Jupyter = 4.0.6
nbgrader = 0.2.2

**Comment by jhamrick** [comment] 2015-11-20 17:38
Hmm, perhaps something changed in between notebook version `4.0.4` (what I have) and `4.0.6`. If I have time I'll try to investigate today, but more likely this weekend.

**Comment by mandli** [comment] 2015-11-20 18:24
Thanks, let me know if you want any examples.

**Comment by jhamrick** [comment] 2015-11-26 04:02
Hmm, so I can't seem to reproduce this. When you run `nbgrader formgrade`, the command line logs should tell you where it is trying to load mathjax from. What does it say there? And are there any mathjax loading errors in the command line logs, or only an error on the browser side of things?

**Comment by mandli** [comment] 2015-11-27 23:35
I just noticed that the mathjax being used is the version from Anaconda.  Is there a way to specify a remote mathjax by chance so I can directly test to see if this is the problem?

**Comment by mandli** [comment] 2015-11-27 23:39
I also noticed this was being displayed:
```
[W 18:38:36.853 FormgradeNotebookApp] Unrecognized JSON config file version, assuming version 1
```

**Comment by Houwang** [comment] 2015-11-30 20:15
I just found out a solution to this issue. Simple way to solve this is to clear cache then restart the browser, I don't know what's the root cause to this issue though.

I noticed that before upgrading OS X to El Capitan, formgrade displayed mathematics fine, but after upgrading and changing some configurations of LaTeX, such annoying errors showed up every time I opened a submission after formgrade. The interesting thing is LaTex renders fine at the first few seconds when I open a submission after formgrade, then the browser seems auto-refreshing or loading something and after that, the errors show up (but not everywhere).  

So, I wonder if it has something to do with the browser cache, since I did formgrade before upgrading the system and changing configurations of LaTeX, maybe something goes wrong when the browser try to load from cache which leads to the errors. That's why I try to clear cache, then restart the browser. Maybe force refresh browser could also work.

**Comment by mandli** [comment] 2015-12-17 16:29
So I found a work around.

Another update on this on my side of things.  As @Houwang pointed out the browser does initially render the mathematics correctly but then appears to refresh and replace the initially rendered text with the `[Math Processing Error]` text.  I think this is just MathJax replacing the temporary images with the proper fonts.  I noticed in the error console though that the following files were not being found
```
[Error] Failed to load resource: the server responded with a status of 404 (NOT FOUND) (fontdata.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (NOT FOUND) (BasicLatin.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (NOT FOUND) (GeneralPunctuation.js, line 0)
```
In my case the "prime" `'` character was the culprit.  I first tried installing manually the latest version of MathJax via 
```
python -m IPython.external.mathjax ~/Downloads/MathJax-2.5-latest.zip` 
```
but that did not work as the version of MathJax being used, as nbgrader helpfully mentioned, was a static version in my anaconda installation.  In my case this was at 
```
~/anaconda/lib/python2.7/site-packages/notebook/static/components/MathJax/MathJax.js
```
Since I was not sure how to point nbgrader somewhere else I instead replaced the installation at the above path with a new (full?) version and everything works now!

I am not sure what the right way to correct this in general is at this point, is it possible to depend on the local IPython installation for MathJax instead of this static version or maybe fall back to one available on the web?

**Comment by jhamrick** [comment] 2016-03-03 04:18
For future reference, you can change the MathJax url by modifying the `FormgradeApp.mathjax_url` config variable. The version that nbgrader uses by default is the local IPython mathjax (though it's now no longer actually under IPython -- it is under the `notebook` package, since the big split).

I am not sure why it would have given you a math processing error, though. It's very strange that this would be an issue after an OS upgrade. Maybe the solution in the future would be to reinstall the `notebook` package?

If anybody else runs into this issue and wants to try investigating other options (rather than just replacing the full mathjax installation) so we can track down the root of the issue, please do let me know! For now, though, I am going to close this issue, since there seems to be a workaround at least and I don't know a good way of proceeding further.

**Closed by jhamrick** 2016-03-03 04:18 UTC
Labels: bug

**Comment by cortner** [comment] 2022-08-30 13:24
just to report this remains a problem on a clean install of conda + nbgrader 0.8.0.
