### ISSUE TITLE
Weird issue with validate button

### ISSUE THREAD

**Issue by whositwhatnow** [jupyter/nbgrader#1066] opened 2019-01-31 14:13 UTC
nbgrader                     0.5.3
jupyterhub                   0.8.0b3  

Strangest bug with the validate button.

Here is an example, but the principle applies to other cells
The question is find how many characters are in the file “opsin.txt”
Its a really simple question:

AA_count = len(open("opsin.txt").read())
print(AA_count)

When you run validate on the NB you get this validation error:

NameError                                 Traceback (most recent call last)
<ipython-input-6-e42ef1ee594b> in <module>()
      1 #CHECK YOUR ANSWER
      2 from lab2 import *
----> 3 count_amino_acids(AA_count)

NameError: name 'AA_count' is not defined
Of course it seems like a typo or something but its not. You can run the same code like this:

AA_count='foo'
AA_count = len(open("opsin.txt").read())
print(AA_count)

And you don’t get a validation error

**Comment by jhamrick** [comment] 2019-05-12 16:06
Hmm, I'm not sure why this would be, but without further information (e.g. the notebook in which this occurs) I can't really provide much help. Can you provide a copy of the notebook that has this problem, and a set of instructions to follow to reproduce the problem?

**Comment by jhamrick** [comment] 2019-08-24 23:18
I am closing this issue because there hasn't been any activity on it in a while. However, if you (or others) continue to encounter problems, feel free to comment here or open a new issue!

**Closed by jhamrick** 2019-08-24 23:18 UTC
Labels: needs info, question
