### ISSUE TITLE
nbgrader release feedback (and show in assignment list)

### ISSUE THREAD

**Issue by nicolairiis** [jupyter/nbgrader#730] opened 2017-03-28 13:20 UTC
Hi,

I think nbgrader should have a command like nbgrader release feedback which transfers the feedback to some exchange service, where students can then fetch it using the assignment list, similar to how they fetch assignments.

I am currently using a python script which generates an ipynb with links to the html feedback files and then (as root) transfers the feedback into a folder in each students home directory.

However this is confusing for students, since they expect to use the assignment list for viewing their feedback.

**Comment by lgpage** [comment] 2017-03-28 16:08
The proposed / needed changes to implement this are discussed in #659

**Comment by jhamrick** [comment] 2017-03-28 17:34
Yes, this is definitely something that we'd like to have. The current implementation of the exchange directory can't support an implementation of this that has appropriate access controls which is why it doesn't exist yet, but hopefully as @lgpage mentioned we'll be able make the changes described in #659 soon in order to have this functionality!

**Comment by jhamrick** [comment] 2017-05-30 22:24
I think this is also a duplicate of #436 so I am going to close this.

**Closed by jhamrick** 2017-05-30 22:24 UTC
Labels: enhancement
