### ISSUE TITLE
Unpining depency on nbconvert 5.6.1?

### ISSUE THREAD

**Issue by nthiery** [jupyter/nbgrader#1411] opened 2021-02-09 16:04 UTC
### `nbgrader --version`

0.7 dev

### Issue

nbgrader is pinning an old version of nbgrader (5.6.1).

https://github.com/jupyter/nbgrader/blob/f5729fb2b6638ea2c6f9b0f9226a0dd7c8cb2ad5/setup.py#L94

Is this a strong dependency? Could it be lifted to allow for nbgrader 6 which
was released in August 2020?

We have a rather fat image for our JupyterHub, and this is putting stress
on the constraints resolution. Also preventing the use of, e.g. voila which
uses nbgrader 6.

Thanks in advance!

**Comment by rkdarst** [comment] 2021-02-09 16:14
there is some discussion in #1369.   #1405 is my attempt to fix it, there are still some template things to fix.  That PR should set someone on the path towards removing it (once they solve the problem there, and any other problems that come up).

I wouldn't count on me having time until mid-year.

**Comment by nthiery** [comment] 2021-02-09 16:17
Ok; thanks for the update!

**Comment by rkdarst** [comment] 2021-02-13 17:38
And just in case it's not clear, I don't mean we will have to wait for
summer, I'm not even a maintainer.  But we can also wonder who would
get to it...

**Comment by nthiery** [comment] 2021-02-19 09:36
Yes, that's how I understood it:-) If I see opportunities to inject a bit of man power there, I'll try!

**Comment by jhamrick** [comment] 2021-03-18 23:02
Thanks for reporting, I think I've just about figured it out in #1421!

Closing as duplicate of #1367

**Closed by jhamrick** 2021-03-18 23:02 UTC
Labels: bug, duplicate

**Comment by nthiery** [comment] 2021-03-19 08:01
Great! Thank you so much @jhamrick . Looking forward to the resolution :-)
