### ISSUE TITLE
这个文档是真的看不懂

### ISSUE THREAD

**Issue by hyh1750522171** [jupyter/nbgrader#1759] opened 2023-03-23 11:49 UTC

**Comment by hyh1750522171** [comment] 2023-03-23 11:55
目前的需求就是，可以实现多人(15个也行，因为服务器性能一般般)同时登录jupyterlab做编程实验，可以，然后教师端可以发布作业(nbgrader)，发布任务，学生去完成，学生完成任务后提交的作业，通过nbgrader自动批改，将结果(可以包括结果分数，完成作业的时间，每一项作业的时间进行统计，)提交到数据库。

目前使用官方的jupyterhub 的docker镜像
https://hub.docker.com/r/jupyterhub/jupyterhub

不清楚不明白这个怎么去使用和配置

**Comment by perllaghu** [comment] 2023-05-02 10:07
[I used google-translate - my apologies if I misunderstand the actual question]

Docker images is making life harder for you...

The problem is that nbgrader assumes all users can copy files to & from a common filestore:

```mermaid
sequenceDiagram
    note over Instructor: Create Assignment
    Instructor->>Instructor: Generate Assignment (removes content from notebooks)
    Instructor->>Exchange: Release Assignment 
    Exchange->>Student: Fetch Assignment
    note over Student: Do Assignment
    Student->>Exchange: Submit
    Exchange->>Instructor: Collect
    Instructor->>Instructor: Autograde (re-inserts content into notebooks)
    note over Instructor: Optional manual grading & adding feedback notes
    Instructor->>Instructor: Generate Feedback
    Instructor->>Exchange: Release Feedback
    Exchange->>Student: Fetch Feedback
```
Your problem is that each docker instance is like a separate computer, so they never share this common "exchange" location.

If all your docker images are running on the same actual computer, you could volume-mount a directory from the hosting computer into the docker image [probably ` /usr/local/share/nbgrader/exchange` - or wherever you define `exchange.root` to be.]

**Comment by brichet** [comment] 2024-03-21 13:07
I'm closing this issue as answered.

Fell free to reopen it if this is not the case.

**Closed by brichet** 2024-03-21 13:07 UTC
