### ISSUE TITLE
Auto-assign zero credit to blank answers

### ISSUE THREAD

**Issue by smeylan** [jupyter/nbgrader#111] opened 2015-03-01 18:30 UTC
Minor enhancement: assign zero credit whenever the written response is just the string 'YOUR ANSWER HERE'

**Comment by jhamrick** [comment] 2015-03-01 19:22
This is kind of a partial duplicate of #91, though this is a bit different since this is about grading rather than comments. The same difficulties still apply, though I think at least we could have a naive solution that gets some cases.

**Closed** 2015-03-08 20:19 UTC
Labels: enhancement, wishlist
