### ISSUE TITLE
Implement support for nbgrader in JupyterLab

### ISSUE THREAD

**Issue by alirezamecheng** [jupyter/nbgrader#1063] opened 2019-01-23 17:01 UTC
Hello,
I saw a video about using nbgrader, and it seems that you have done a great job. 
I was wondering if it is possible to install nbgrader extension for `JupyterLab` within the jupyterhub?
Can you please help me, how to do that?
thanks for your time.

**Comment by leonsp** [comment] 2019-04-01 21:54
I second this question.

**Comment by jhamrick** [comment] 2019-05-12 17:22
Unfortunately at the moment JupyterLab support is not yet available.

**Comment by jhamrick** [comment] 2019-05-28 22:13
I am going to close this as a duplicate of #1006

**Closed by jhamrick** 2019-05-28 22:13 UTC
Labels: enhancement, important, refactor
