### ISSUE TITLE
Hide test cell 

### ISSUE THREAD

**Issue by nadimmajed** [jupyter/nbgrader#685] opened 2017-02-02 23:14 UTC
Hello everybody,
I want to make test cell hidden for the student version. 
I saw two solutions for this problem. The first is to use '### BEGIN TEST' and '### END TEST'
and the second is to modify the preprocessor file. Can anybody walk me through one of them.
Thankyou in advance

**Comment by lgpage** [comment] 2017-02-02 23:26
@nadimmajed there is an open PR for this feature which will hopefully be added soon (see #681 )

**Comment by lgpage** [comment] 2017-02-02 23:27
This is a duplicate of #390 so I will close this to track the issue there.

**Closed** 2017-02-02 23:27 UTC
Labels: duplicate

**Comment by nadimmajed** [comment] 2017-02-02 23:48
@jhamrick, you said in the issue #390 that we can use  ### BEGIN TEST and ### END TEST in order to hide tests in student version. Is there any configuration that I should do before using them?
Thankyou in advance

**Comment by lgpage** [comment] 2017-02-03 00:03
@nadimmajed at the moment this feature does not exist in nbgrader. Simply using the ``### BEGIN TEST`` and ``### END TEST`` delimiters will not do anything. PR #681 introduces these new delimiters as well as a new preprocessor (for the AssignApp) that uses these delimiters to strip away tests for the student version.

**Comment by nadimmajed** [comment] 2017-02-03 00:07
Thank you very much for your clarification. How long approximately will it take for the new feature to be added?

**Comment by lgpage** [comment] 2017-02-03 00:11
Not sure, all relevant changes have been made in PR #681 and it is awaiting review from @jhamrick (who is a bit swamped with work at the moment), but hopefully soon.

**Comment by nadimmajed** [comment] 2017-02-03 00:12
Thank you for your time.
