### ISSUE TITLE
Generate assignments from a folder structure with subfolders

### ISSUE THREAD

**Issue by DerFerdi** [jupyter/nbgrader#1242] opened 2019-10-10 11:28 UTC
Hi,
I have a small problem using nbgrader on Jupyterhub.
I am using following versions:

Ubuntu 18.04

Nbgrader 0.6.0

Jupyterhub 1.0.0 (tljh)

Jupyter Notebook 5.7.8

I'm trying to generate assignments from a folder structure with subfolders. So my source folder looks something like this:
./source/assignment_1
./source/assignment_1/folder_1
./source/assignment_1/folder_2

When executing "nbgrader generate_assignment" only the ipynb-files in the folder assignment_1 are converted and copied to the release folder. The files in folder_1 and folder_2 are ignored.

I already tried to add the --CourseDirectory.include=['**'] option to "nbgrader generate_assignment" as well as to the config file. However, the ipynb-files in the subfolders are still ignored.

Any idea why this is the case? Am I missing some necessary config option?

Thanks in advance :)

**Comment by perllaghu** [comment] 2019-10-15 09:44
It's actually hard-coded into the system... see the documentation at https://github.com/jupyter/nbgrader/blob/master/nbgrader/apps/generateassignmentapp.py#L54 for the `generate` step

**Comment by jhamrick** [comment] 2019-11-02 09:59
I think this is also a duplicate of #1223

**Closed by jhamrick** 2019-11-02 09:59 UTC
