### ISSUE TITLE
empty answers are not graded automatically

### ISSUE THREAD

**Issue by svenuthe** [jupyter/nbgrader#993] opened 2018-07-11 14:20 UTC
### Operating system
Fedora

### `nbgrader --version`
python 3.5.3
nbgrader 0.5.4

### `jupyterhub --version` (if used with JupyterHub)
4.4.0

### `jupyter notebook --version` 
5.4.1

### Expected behaviour
When a student's answer is empty, the field credit form is not shown.
The credit should evaluate automatically to zero.

### Actual behaviour
When a student's answer is empty, the field credit form is not shown.
The submission still shows that it need manual grading.

### Steps to reproduce the behaviour
Submit an empty answer field.
Autograde submission.
Manual grade submission (insert credits for all other answers).
List all Submission: The submission still needs grading.

**Comment by jhamrick** [comment] 2018-10-06 13:31
Could you send me a copy of a notebook where you have this problem? It's not something I am currently able to reproduce.

**Comment by jhamrick** [comment] 2018-12-15 19:07
I am closing this issue because there hasn't been any activity on it in a while. However, if you (or others) continue to encounter problems, feel free to comment here or open a new issue!

**Closed by jhamrick** 2018-12-15 19:07 UTC
Labels: needs info
