### ISSUE TITLE
Standalone workflow

### ISSUE THREAD

**Issue by psychemedia** [jupyter/nbgrader#966] opened 2018-05-14 22:02 UTC
My distance ed institution is some way to go yet with a centralised notebook service, but we do currently have a course running with:

- ~500 students working with individual notebook servers running in VMs on their own computers;
- ~20 tutors/markers each with an allocation of about ~25 students; markers are also running their own VMs on their own hardware.
- 3 pieces of assessed work: in the first two, each assessment is set using separate questions spread across ~3 notebooks per assessment; the last assessment is a data investigation report.

I'm looking to find a way of using nbgrader to set and manually mark / comment on notebook based assessments.

Ideally, I'd like a process something along the lines of:

- central academic team create assessment notebook(s) for manual grading and with marking guide annoations; 
- central academic team export notebook files stripped of marking guide notes that can be published as static files on VLE and downloaded by students from there; annotated notebooks with marking guidance are exported for download by markers from tutor area of VLE.
- student to enter an ID number and name into their notebook assessed notebooks, run the notebooks, zip them and then submit the zip file as an attachment through our legacy online assessment handling tools;
- tutor/markers to use our legacy assessment handling tool to download zip files containing submissions from each of their students; (we don't control the zip structure of the outer layer which is of the form courseCode/assignmentCode/tutorID/region/studentID)
- markers point grading tool at downloaded student files and load them into grading tool showing assignment/student listing; 
- markers manually mark and comment on notebook assignments;
- marked/annotated notebooks are pushed back into our legacy marking tool directory structure and returned using legacy tools;
- students collect annotated notebooks from legacy system and inspect notebooks. Marker comments should be clearly highlighted.

(We might be able to fudge the return handler by building a custom return handler that bundles files in the way the legacy online assignment handling tool expects.)

What I'm not sure is how to tease out / configure just the bits of nbgrader we need to make to support this workflow wherever we can?

**Comment by jhamrick** [comment] 2018-05-19 13:28
This should certainly be feasible with nbgrader, for the most part.

> central academic team create assessment notebook(s) for manual grading and with marking guide annoations;

You'll want to set up a shared notebook server (not a full JupyterHub---just the notebook which is running at a URL that multiple people can access). Then your central academic team can use that notebook server to create the instructor versions of your assignments. Alternately, you can have the team all install nbgrader separately and contribute notebooks by e.g. pushing to a git repository that hosts them. But you will need the shared server anyway for grading, so it might be easier just to do that.

> central academic team export notebook files stripped of marking guide notes that can be published as static files on VLE and downloaded by students from there; annotated notebooks with marking guidance are exported for download by markers from tutor area of VLE.


student to enter an ID number and name into their notebook assessed notebooks, run the notebooks, zip them and then submit the zip file as an attachment through our legacy online assessment handling tools;
tutor/markers to use our legacy assessment handling tool to download zip files containing submissions from each of their students; (we don't control the zip structure of the outer layer which is of the form courseCode/assignmentCode/tutorID/region/studentID)
markers point grading tool at downloaded student files and load them into grading tool showing assignment/student listing;
markers manually mark and comment on notebook assignments;
marked/annotated notebooks are pushed back into our legacy marking tool directory structure and returned using legacy tools;
students collect annotated notebooks from legacy system and inspect notebooks. Marker comments should be clearly highlighted.

**Comment by jhamrick** [comment] 2018-05-19 13:35
This should certainly be feasible with nbgrader, for the most part.

> central academic team create assessment notebook(s) for manual grading and with marking guide annoations;

You'll want to set up a shared notebook server (not a full JupyterHub---just the notebook which is running at a URL that multiple people can access). Then your central academic team can use that notebook server to create the instructor versions of your assignments. Alternately, you can have the team all install nbgrader separately and contribute notebooks by e.g. pushing to a git repository that hosts them. But you will need the shared server anyway for grading, so it might be easier just to do that.

> central academic team export notebook files stripped of marking guide notes that can be published as static files on VLE and downloaded by students from there; annotated notebooks with marking guidance are exported for download by markers from tutor area of VLE.

nbgrader doesn't have any explicit way to have rubrics/marking guidance, but what I've done in the past is to put marking guidelines in the "solution" regions. So these regions will get removed when running `nbgrader assign`, and so the students won't see them, and you can distribute the source version of the notebook to markers so they can see the guidelines.

> student to enter an ID number and name into their notebook assessed notebooks, run the notebooks, zip them and then submit the zip file as an attachment through our legacy online assessment handling tools;
>
> tutor/markers to use our legacy assessment handling tool to download zip files containing submissions from each of their students; (we don't control the zip structure of the outer layer which is of the form courseCode/assignmentCode/tutorID/region/studentID)
>
> markers point grading tool at downloaded student files and load them into grading tool showing assignment/student listing;

The `nbgrader zip_collect` command was designed to help with exactly this! See: http://nbgrader.readthedocs.io/en/stable/user_guide/managing_assignment_files_manually.html

> markers manually mark and comment on notebook assignments;

As I mentioned earlier, for multiple graders you'll need a shared notebook server running the formgrader which all the graders can access.

> marked/annotated notebooks are pushed back into our legacy marking tool directory structure and returned using legacy tools;

After doing the manual grading, you can run `nbgrader feedback` to generate html feedback on the notebooks. But here is where you'll need to do a bit of custom scripting to upload them back to system.

> students collect annotated notebooks from legacy system and inspect notebooks. Marker comments should be clearly highlighted.

In the HTML versions of feedback notebooks, comments are clearly highlighted. Unfortunately, nbgrader doesn't currently support inserting comments directly into the actual notebooks.

**Comment by jhamrick** [comment] 2018-10-07 19:45
I am going to close this since there hasn't been any activity on this issue for a while, but feel free to open new issues if there are specific things you need addressed!

**Closed by jhamrick** 2018-10-07 19:45 UTC
Labels: question
