### ISSUE TITLE
Manage Groups BUG

### ISSUE THREAD

**Issue by Nethramudhiraj** [jupyter/nbgrader#1869] opened 2024-03-20 08:30 UTC
For admin login, in the hub control panel->Admin->Manage Groups, 
If there are existing users in a particular group, when we open the group and click on apply without adding any new user, the existing users are getting deleted.
You can view that the users are deleted once you come back(by clicking on Back beside the Apply button), there you will see 0 users beside that group.

**Comment by lahwaacz** [comment] 2024-03-23 16:58
You have reported the issue in the wrong place, the _hub control panel->Admin->Manage Groups_ interface is part of [jupyterhub](https://github.com/jupyterhub/jupyterhub/), not nbgrader.

Nevertheless, I can't reproduce the problem with jupyterhub 4.1.0.

**Comment by brichet** [comment] 2024-04-09 07:35
I'm closing this issue.

Feel free to open it again if you think that it should be fixed in nbgrader.

**Closed by brichet** 2024-04-09 07:35 UTC
