### ISSUE TITLE
problem with nbgrader release

### ISSUE THREAD

**Issue by nadimmajed** [jupyter/nbgrader#676] opened 2017-01-24 00:35 UTC
Hello, 
I am using Anaconda4.2 with python3.5
I have used those commands to install nbgrader

       conda install -c conda-forge nbgrader
       pip install git+git://github.com/jupyter/nbgrader.git
       jupyter nbextension install --sys-prefix --py nbgrader
       jupyter nbextension enable --sys-prefix --py nbgrader
       jupyter serverextension enable --sys-prefix --py nbgrader

I have modified nbgrader_config.py to be like : 

       c = get_config()
       c.NbGrader.course_id = "example_course"
       c.TransferApp.exchange_directory = "/tmp/exchange"

when I run :

      nbgrader assign ps1 

everything seems ok 
but when  I run :

       nbgrader release ps1

I get this error
 [ReleaseApp | ERROR] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange

Can you please tell me what should I do? 
Thankyou very much

**Comment by jhamrick** [comment] 2017-01-24 01:24
As described [here](http://nbgrader.readthedocs.io/en/stable/user_guide/managing_assignment_files.html) the exchange directory must be readable and writable by all users. Try running:

```
chmod ugo+rw /srv/nbgrader/exchange
```

and then re-running `nbgrader release`.

**Comment by nadimmajed** [comment] 2017-01-24 08:17
Even when I have modified nbgrader_config.py in order to use /tmp/exchange , it asked me again for /srv/nbgrader/exchange. So, I have created /srv/nbgrader/exchange and it worked.
Thankyou very much.

**Comment by jhamrick** [comment] 2017-01-25 18:17
That shouldn't be the case... possibly a bug? Can you change your nbgrader config to use `/tmp/exchange`, and then run `nbgrader` with the `--debug` flag and paste the output?

**Comment by nadimmajed** [comment] 2017-01-25 23:57
I know now what I did wrong, I have modified the **nbgrader_config.py** which was in the _nbgrader_demo_ folder. I read the documentation again and it said that I need to modify the **nbgrader_config.py** that was "automatically loaded when we run nbgrader" which is in  the _instructor_ folder and it worked fine. 
Thankyou very much for your efforts.

**Comment by jhamrick** [comment] 2017-01-26 02:12
Great, glad you were able to figure it out! I will close this issue, but feel free to open other issues if you run into any more problems.

**Closed by jhamrick** 2017-01-26 02:12 UTC
Labels: question

**Comment by sukhjitsehra** [comment] 2020-03-30 13:39
Hi 

I am using TLJH + NBGRADER for assignment release and collection. 
I have used three versions of https://nbgrader.readthedocs.io/en/stable/configuration/nbgrader_config.html as described on the help page. 

Then I try to run "nbgrader release_assignment ps1 --force --debug" and sees the following.

> jupyter-jupytertljh-admin@CseServer:~/course_id$ nbgrader release_assignment ps1 --force --debug
[ReleaseAssignmentApp | DEBUG] Searching ['/home/jupyter-jupytertljh-admin/course_id', '/home/jupyter-jupytertljh-admin/.jupyter', '/opt/tljh/user/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[ReleaseAssignmentApp | DEBUG] Looking for jupyter_config in /etc/jupyter
[ReleaseAssignmentApp | DEBUG] Looking for jupyter_config in /usr/local/etc/jupyter
[ReleaseAssignmentApp | DEBUG] Looking for jupyter_config in /opt/tljh/user/etc/jupyter
[ReleaseAssignmentApp | DEBUG] Looking for jupyter_config in /home/jupyter-jupytertljh-admin/.jupyter
[ReleaseAssignmentApp | DEBUG] Looking for jupyter_config in /home/jupyter-jupytertljh-admin/course_id
[ReleaseAssignmentApp | DEBUG] Looking for nbgrader_config in /etc/jupyter
[ReleaseAssignmentApp | DEBUG] Looking for nbgrader_config in /usr/local/etc/jupyter
[ReleaseAssignmentApp | DEBUG] Looking for nbgrader_config in /opt/tljh/user/etc/jupyter
[ReleaseAssignmentApp | DEBUG] Loaded config file: /opt/tljh/user/etc/jupyter/nbgrader_config.py
[ReleaseAssignmentApp | DEBUG] Looking for nbgrader_config in /home/jupyter-jupytertljh-admin/.jupyter
[ReleaseAssignmentApp | DEBUG] Loaded config file: /home/jupyter-jupytertljh-admin/.jupyter/nbgrader_config.py
[ReleaseAssignmentApp | DEBUG] Looking for nbgrader_config in /home/jupyter-jupytertljh-admin/course_id
[ReleaseAssignmentApp | DEBUG] Loaded config file: /home/jupyter-jupytertljh-admin/course_id/nbgrader_config.py
[ReleaseAssignmentApp | DEBUG] Looking for nbgrader_config in /home/jupyter-jupytertljh-admin/course_id
[ReleaseAssignmentApp | DEBUG] Loaded config file: /home/jupyter-jupytertljh-admin/course_id/nbgrader_config.py
[ReleaseAssignmentApp | DEBUG] Using authenticator: NoAuthPlugin
[ReleaseAssignmentApp | INFO] Overwriting files: /home/jupyter-jupytertljh-admin/course_id ps1
[ReleaseAssignmentApp | INFO] Source: /home/jupyter-jupytertljh-admin/course_id/release/./ps1
[ReleaseAssignmentApp | INFO] Destination: /home/jupyter-jupytertljh-admin/course_id/outbound/ps1
[ReleaseAssignmentApp | INFO] Released as: /home/jupyter-jupytertljh-admin/course_id ps1


The issue is that the command is not writing into /srv/nbgrader/exchange, that has been given permissions as:
> chmod ugo+rw /srv/nbgrader/exchange

Can you please assist in resolving 

Thanks
