### ISSUE TITLE
Add import Students option in Formgrader app

### ISSUE THREAD

**Issue by whositwhatnow** [jupyter/nbgrader#1214] opened 2019-09-12 13:25 UTC
Possible to add a link or function to add a bulk list of students in the forgrader app.

**Comment by jhamrick** [comment] 2019-11-02 09:09
Yes, it would definitely be nice to have this! But this is a duplicate of #810 , so I will close this in favor of the other one.

**Closed by jhamrick** 2019-11-02 09:09 UTC
